docker.image = "docker.int.esrlabs.com/bsw-documentation:2024-01-03"

script = """
    ruby doc/footer.rb
"""

doc.path = "doc"
doc.name = "Eclipse OpenBSW Documentation"
doc.reportFolder = "doc"

codeFormat = false
