dockerfile.filename = "bsw-arm"

script = """
    cmake -B cmake-build-s32k148-freertos -S executables/referenceApp -DBUILD_TARGET_PLATFORM="S32K148EVB" -DBUILD_TARGET_RTOS="FREERTOS" --toolchain ../../admin/cmake/ArmNoneEabi-gcc.cmake
    cmake --build cmake-build-s32k148-freertos --target app.referenceApp -j
"""

codeFormat = false
