# *******************************************************************************
# Copyright (c) 2026 Accenture
# Copyright (c) 2026 BMW AG
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//libs/bsw/middleware:__subpackages__"])

# ===========================================================================
# Core targets
# ===========================================================================

filegroup(
    name = "core_headers",
    srcs = [
        "include/middleware/core/ClusterConnection.h",
        "include/middleware/core/ClusterConnectionBase.h",
        "include/middleware/core/DatabaseManipulator.h",
        "include/middleware/core/EventSender.h",
        "include/middleware/core/Future.h",
        "include/middleware/core/IClusterConnection.h",
        "include/middleware/core/IClusterConnectionConfigurationBase.h",
        "include/middleware/core/ITimeoutHandler.h",
        "include/middleware/core/InstancesDatabase.h",
        "include/middleware/core/LoggerApi.h",
        "include/middleware/core/Message.h",
        "include/middleware/core/MessagePayloadBuilder.h",
        "include/middleware/core/ProxyAttribute.h",
        "include/middleware/core/ProxyAttributeBase.h",
        "include/middleware/core/ProxyBase.h",
        "include/middleware/core/ProxyEventBase.h",
        "include/middleware/core/ResponseBuffer.h",
        "include/middleware/core/ResponseBufferBase.h",
        "include/middleware/core/SkeletonAttribute.h",
        "include/middleware/core/SkeletonBase.h",
        "include/middleware/core/SkeletonEvent.h",
        "include/middleware/core/TransceiverBase.h",
        "include/middleware/core/TransceiverContainer.h",
        "include/middleware/core/types.h",
        "include/middleware/rpc/ProxyFireAndForgetMethod.h",
        "include/middleware/rpc/ProxyMethod.h",
        "include/middleware/rpc/ProxyMethodImpl.h",
    ],
)

filegroup(
    name = "core_srcs",
    srcs = [
        "src/middleware/core/ClusterConnection.cpp",
        "src/middleware/core/ClusterConnectionBase.cpp",
        "src/middleware/core/DatabaseManipulator.cpp",
        "src/middleware/core/EventSender.cpp",
        "src/middleware/core/IClusterConnectionConfigurationBase.cpp",
        "src/middleware/core/LoggerApi.cpp",
        "src/middleware/core/MessagePayloadBuilder.cpp",
        "src/middleware/core/ProxyBase.cpp",
        "src/middleware/core/ResponseBufferBase.cpp",
        "src/middleware/core/SkeletonBase.cpp",
        "src/middleware/rpc/ProxyFireAndForgetMethod.cpp",
        "src/middleware/rpc/ProxyMethodImpl.cpp",
    ],
)

cc_library(
    name = "core",
    srcs = [":core_srcs"],
    hdrs = [":core_headers"],
    strip_include_prefix = "include",
    deps = [
        ":memory",
        "//libs/3rdparty/etl",
        "//libs/bsw/middleware/interfaces:logger",
        "//libs/bsw/middleware/interfaces:os",
        "//libs/bsw/middleware/interfaces:time",
    ],
)

filegroup(
    name = "core_code_to_doc",
    srcs = [
        ":core_headers",
        ":core_srcs",
    ],
    visibility = ["//visibility:public"],
)

# ===========================================================================
# Memory targets
# ===========================================================================

filegroup(
    name = "memory_headers",
    srcs = [
        "include/middleware/memory/Aggregator.h",
        "include/middleware/memory/AllocatorBase.h",
        "include/middleware/memory/AllocatorSelector.h",
        "include/middleware/memory/AllocatorTypes.h",
        "include/middleware/memory/Pool.h",
        "include/middleware/memory/PoolBase.h",
        "include/middleware/memory/impl/PoolIndexBySize.h",
        "include/middleware/memory/impl/TupleSelectionSort.h",
    ],
)

filegroup(
    name = "memory_srcs",
    srcs = [
        "src/middleware/memory/PoolBase.cpp",
    ],
)

cc_library(
    name = "memory",
    srcs = [":memory_srcs"],
    hdrs = [":memory_headers"],
    strip_include_prefix = "include",
    deps = [
        "//libs/3rdparty/etl",
        "//libs/bsw/middleware/interfaces:concurrency",
    ],
)

filegroup(
    name = "memory_code_to_doc",
    srcs = [
        ":memory_headers",
        ":memory_srcs",
    ],
    visibility = ["//visibility:public"],
)

# ===========================================================================
# Queue targets
# ===========================================================================

filegroup(
    name = "queue_headers",
    srcs = [
        "include/middleware/queue/Queue.h",
        "include/middleware/queue/QueueBase.h",
    ],
)

cc_library(
    name = "queue",
    hdrs = [":queue_headers"],
    strip_include_prefix = "include",
    deps = ["//libs/3rdparty/etl"],
)

filegroup(
    name = "queue_code_to_doc",
    srcs = [":queue_headers"],
    visibility = ["//visibility:public"],
)

# ===========================================================================
# Middleware lib targets
# ===========================================================================

cc_library(
    name = "middleware",
    visibility = ["//visibility:public"],
    deps = [
        ":core",
        ":memory",
        ":queue",
        "//libs/bsw/middleware/interfaces:concurrency_impl",
        "//libs/bsw/middleware/interfaces:logger_impl",
        "//libs/bsw/middleware/interfaces:os_impl",
        "//libs/bsw/middleware/interfaces:time_impl",
    ],
)
