# *******************************************************************************
# Copyright (c) 2026 Accenture
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//libs/bsw/middleware:configurable_middleware.bzl", "middleware_config")
load(
    "//libs/bsw/middleware/tools/cpp_generator:middleware_codegen.bzl",
    "middleware_codegen",
)
load(":generated_outputs.bzl", "GENERATED_OUTPUTS")

package(default_visibility = ["//executables/referenceApp/middlewareConfiguration:__subpackages__"])

# ---------------------------------------------------------------------------
# ReferenceApp Platform integration targets
# ---------------------------------------------------------------------------

cc_library(
    name = "concurrency_impl",
    hdrs = ["include/platform_integration/middleware/concurrency/lock_types.h"],
    strip_include_prefix = "include/platform_integration",
)

cc_library(
    name = "logger_impl",
    srcs = ["src/platform_integration/logger/LoggerImpl.cpp"],
    deps = [
        "//executables/referenceApp/application:demo_logger",
        "//libs/3rdparty/etl",
        "//libs/bsw/logger",
        "//libs/bsw/middleware/interfaces:logger",
        "//libs/bsw/util",
    ],
)

cc_library(
    name = "os_impl",
    srcs = ["src/platform_integration/os/OsDefinitions.cpp"],
    deps = [
        "//executables/referenceApp/asyncBinding:async_binding",
        "//libs/bsw/middleware/interfaces:os",
    ],
)

cc_library(
    name = "time_impl",
    srcs = ["src/platform_integration/time/SystemTimeProvider.cpp"],
    deps = [
        "//libs/bsw/bsp",
        "//libs/bsw/middleware/interfaces:time",
    ],
)

# ---------------------------------------------------------------------------
# ReferenceApp code generation targets
# ---------------------------------------------------------------------------

middleware_codegen(
    name = "middleware_configuration_generated",
    deployment_yaml = "model/deployment.yaml",
    generated_outputs = GENERATED_OUTPUTS,
    deps = ["//libs/bsw/middleware"],
)

# ---------------------------------------------------------------------------
# ReferenceApp middleware configuration targets
# ---------------------------------------------------------------------------

cc_library(
    name = "middleware_impl",
    srcs = [
        "src/MemoryLayout.cpp",
    ],
    hdrs = ["include/MemoryLayout.h"],
    strip_include_prefix = "include",
    deps = [":middleware_configuration_generated"],
)

middleware_config(
    name = "middleware_configuration",
    config = {
        "//libs/3rdparty/etl:etl_profile": "//executables/referenceApp/etl_profile:etl_profile",
        "//libs/bsw/middleware/interfaces:concurrency_impl": ":concurrency_impl",
        "//libs/bsw/middleware/interfaces:logger_impl": ":logger_impl",
        "//libs/bsw/middleware/interfaces:os_impl": ":os_impl",
        "//libs/bsw/middleware/interfaces:time_impl": ":time_impl",
    },
    dep = ":middleware_impl",
    visibility = ["//visibility:public"],
)
