# *******************************************************************************
# Copyright (c) 2026 Accenture
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//bazel/config/build_variant:compatibility.bzl", "unit_test_only")

label_flag(
    name = "routing_configuration",
    build_setting_default = "//executables/referenceApp/configuration:routing_configuration_headers",
    visibility = ["//visibility:public"],
)

label_flag(
    name = "routing_blob_configuration",
    build_setting_default = "//libs/bsw/routing:routing_test_blob_configuration",
    visibility = ["//visibility:public"],
)

alias(
    name = "routing",
    actual = "//libs/bsw/routing/core:routing",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "routing_test_configuration",
    hdrs = [
        "test/include/routing/channelId.h",
        "test/include/routing/constants.h",
        "test/include/routing/definition.h",
    ],
    strip_include_prefix = "test/include",
    target_compatible_with = unit_test_only(),
    visibility = ["//visibility:public"],
)

cc_library(
    name = "routing_test_blob_configuration",
    hdrs = [
        "test/include/blob/ConfigType.h",
        "test/include/blob/configuration.h",
    ],
    strip_include_prefix = "test/include",
    target_compatible_with = unit_test_only(),
    visibility = ["//visibility:public"],
)
