name: Publish Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-sphinx-docs:
    uses: ./.github/workflows/sphinx-doc-build.yml

  publish-docs:
    runs-on: ubuntu-latest
    needs: build-sphinx-docs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Sphinx documentation
        uses: actions/download-artifact@v4
        with:
          name: sphinx_docs
          path: ./doc/github_pages

      - name: Unzip Sphinx documentation
        working-directory: ./doc/github_pages
        run: |
          unzip sphinx_docs.zip
          rm sphinx_docs.zip

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/github_pages
          force_orphan: true
