name: Build Documentation

on: [workflow_call, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./doc
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install plantuml
      run: |
        sudo apt-get update
        sudo apt-get install -y plantuml

    - name: Build Sphinx documentation
      run: make html OFFICIAL_BUILD=1

    - name: Copy redirection index.html
      run: cp github_pages/redirect_index.html build/html/index.html

    - name: Zip documentation
      run: |
        mv build/html docs
        zip -r docs.zip docs

    - name: Upload docs
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: ./doc/docs.zip
