name: Integration Tests

on: [ merge_group, pull_request, push ]

jobs:
  integration-test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      # - uses: self-actuated/connect-ssh@master
      # - uses: mxschmitt/action-tmate@v3
      - run: nix flake check --print-build-logs .
